// LLMModelDialog.tsx
import { useState, useEffect, FC } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Alert, AlertTitle } from '@/components/ui/alert';
import { AlertCircleIcon } from 'lucide-react';
import { useTenantFetch } from '@/hooks/use-tenant-fetch';
import { useI18n } from '@/app/providers/i18n';

interface LLMModelDialogProps {
  isAdd: boolean;
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
  llmConfig: LlmConfig;
  onSaveSuccess: (llm: LlmConfig) => void;
}

interface LlmConfig {
  id: string;
  model_id: string;
  source: string;
  model: string;
  api_key: string;
  base_url: string;
  max_context: number;
  context_window: number;
  max_tokens: number;
  enabled: boolean;
  vision_support: boolean;
  enable_thinking: boolean;
  temperature: number;
}

export const LLMModelDialog: FC<LLMModelDialogProps> = ({
  isAdd,
  isOpen,
  setIsOpen,
  llmConfig,
  onSaveSuccess,
}) => {
  const { t } = useI18n();
  const [llm, setLlm] = useState<LlmConfig>(llmConfig);
  const [saveErrorMsg, setSaveErrorMsg] = useState('');
  const [modelIdEdited, setModelIdEdited] = useState(false);
  const { tenantFetch } = useTenantFetch();

  // Freeze isAdd while the dialog is closing (prevents title flicker
  // between "Add" and "Edit" during close animation).
  const [displayIsAdd, setDisplayIsAdd] = useState(isAdd);
  useEffect(() => {
    if (isOpen) setDisplayIsAdd(isAdd);
  }, [isOpen, isAdd]);

  useEffect(() => {
    setLlm(llmConfig);
    setModelIdEdited(false);
  }, [isAdd, llmConfig]);

  useEffect(() => {
    setSaveErrorMsg('');
  }, [llm]);

  const handleSubmit = async () => {
    setSaveErrorMsg('');
    const submitData = {
      ...llm,
      model_id: llm.model_id || llm.model,
    };
    if (!submitData.model || (isAdd && !submitData.api_key) || !submitData.base_url || !submitData.model_id) {
      setSaveErrorMsg(t('config.model.fillCompleteInfo'));
      return;
    }
    const submit_url = isAdd ? `/api/config/llms` : `/api/config/llms/${llm.id}`;
    const updateMethod = isAdd ? 'POST' : 'PUT';
    if (submitData.api_key === '******') submitData.api_key = '';
    try {
      const res = await tenantFetch(submit_url, {
        method: updateMethod,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(submitData),
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => null);
        const detail = errorData?.message || errorData?.detail || errorData?.error;
        setSaveErrorMsg(detail || t('config.model.requestFailedCheckInfo', { method: updateMethod }));
        return;
      }
      const jsondata = await res.json();
      onSaveSuccess(jsondata.data as LlmConfig);
      setIsOpen(false);
    } catch (err: any) {
      setSaveErrorMsg(t('config.model.requestFailed', { method: updateMethod }));
    }
  };

  const handleDialogClose = (open: boolean) => {
    setIsOpen(open);
    if (!open) setSaveErrorMsg('');
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleDialogClose}>
      <DialogContent className="sm:max-w-[640px] flex flex-col max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <span className="type-corner-badge type-llm">LLM</span>
            {displayIsAdd ? 'Add LLM' : 'Edit LLM'}
          </DialogTitle>
          <DialogDescription>
            Provide your provider credentials — the model ID follows the model name by default
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2 flex-1 min-h-0 overflow-y-auto -mx-6 px-6">
          <div className="model-field-guide">
            <div>
              <span className="guide-label">Provider requires</span>
              <span className="guide-value">base_url / api_key / model</span>
            </div>
            <div>
              <span className="guide-label">Auto-generated by NexaMind AI</span>
              <span className="guide-value">model_id = model</span>
            </div>
          </div>

          {/* Provider section */}
          <div>
            <div className="dialog-section-title">Provider connection</div>
            <div className="space-y-3">
              <div>
                <label htmlFor="base_url" className="form-label">
                  Base URL
                  <span className="required">*</span>
                </label>
                <Input
                  id="base_url"
                  list="base_url_options"
                  placeholder="https://dashscope.aliyuncs.com/compatible-mode/v1"
                  value={llm?.base_url ?? ''}
                  onChange={(e) => setLlm((prev) => ({ ...prev, base_url: e.target.value }))}
                />
                <p className="field-hint">OpenAI-compatible base URL, usually ending in /v1.</p>
                <datalist id="base_url_options">
                  <option value="https://api.openai.com/v1">OpenAI</option>
                  <option value="https://dashscope.aliyuncs.com/compatible-mode/v1">
                    {t('config.model.qwenModel')}
                  </option>
                </datalist>
              </div>

              <div>
                <label htmlFor="api_key" className="form-label">
                  API Key
                  <span className="required">*</span>
                </label>
                <Input
                  id="api_key"
                  type="password"
                  placeholder="sk-..."
                  value={isAdd ? (llm?.api_key ?? '') : (llm?.api_key || '******')}
                  onChange={(e) => setLlm((prev) => ({ ...prev, api_key: e.target.value }))}
                />
                <p className="field-hint">Provider auth key — only fill when adding or rotating it.</p>
              </div>

              <div>
                <label htmlFor="model" className="form-label">
                  Provider model name <span className="field-code">model</span>
                  <span className="required">*</span>
                </label>
                <Input
                  id="model"
                  placeholder="gpt-4o / qwen3-plus"
                  value={llm?.model ?? ''}
                  onChange={(e) => {
                    const model = e.target.value;
                    setLlm((prev) => ({
                      ...prev,
                      model,
                      model_id: isAdd && !modelIdEdited ? model : prev.model_id,
                    }));
                  }}
                />
                <p className="field-hint">Model name sent to the provider, e.g. gpt-4o, qwen3-plus.</p>
              </div>
            </div>
          </div>

          {/* Identity section */}
          <div>
            <div className="dialog-section-title">NexaMind AI identity (optional)</div>
            <div className="space-y-3">
              <div>
                <label htmlFor="model_id" className="form-label">
                  NexaMind AI model ID <span className="field-code">model_id</span>
                  <span className="required">*</span>
                </label>
                <Input
                  id="model_id"
                  placeholder={llm?.model || 'Defaults to the provider model name'}
                  value={llm?.model_id ?? ''}
                  onChange={(e) => {
                    setModelIdEdited(true);
                    setLlm((prev) => ({ ...prev, model_id: e.target.value }));
                  }}
                />
                <p className="field-hint">Follows the provider model name by default; if left empty the model name is saved. If a conflict is reported, use a distinct ID such as qwen3-plus-think / qwen3-plus-nothink.</p>
              </div>
            </div>
          </div>

          {/* Advanced section */}
          <div>
            <div className="dialog-section-title">Advanced</div>
            <div className="space-y-2">
              <div className="form-row-inline">
                <div className="form-row-inline-label">
                  <span className="title">{t('config.model.visionModel')}</span>
                  <span className="hint">Supports image input</span>
                </div>
                <Switch
                  id="vision_support"
                  checked={llm?.vision_support ?? false}
                  onCheckedChange={(checked) =>
                    setLlm((prev) => ({ ...prev, vision_support: checked }))
                  }
                />
              </div>

              <div className="form-row-inline">
                <div className="form-row-inline-label">
                  <span className="title">{t('config.model.thinkingModel')}</span>
                  <span className="hint">Enable chain-of-thought reasoning</span>
                </div>
                <Switch
                  id="enable_thinking"
                  checked={llm?.enable_thinking ?? false}
                  onCheckedChange={(checked) =>
                    setLlm((prev) => ({ ...prev, enable_thinking: checked }))
                  }
                />
              </div>

              <div className="form-row-inline">
                <div className="form-row-inline-label">
                  <span className="title">{t('config.model.temperature')}</span>
                  <span className="hint">{t('config.model.temperatureHint')}</span>
                </div>
                <Input
                  id="temperature"
                  type="number"
                  step="0.1"
                  min="0"
                  max="2"
                  value={llm?.temperature ?? 0.1}
                  onChange={(e) => {
                    const val = parseFloat(e.target.value);
                    setLlm((prev) => ({
                      ...prev,
                      temperature: isNaN(val) || val < 0 ? 0.1 : val,
                    }));
                  }}
                  className="w-20 h-8 text-right"
                />
              </div>

              <div className="form-row-inline">
                <div className="form-row-inline-label">
                  <span className="title">Context Window</span>
                  <span className="hint">Max context length (tokens)</span>
                </div>
                <Input
                  id="context_window"
                  type="number"
                  step="1000"
                  min="1000"
                  value={llm?.context_window ?? 110000}
                  onChange={(e) => {
                    const val = parseInt(e.target.value);
                    setLlm((prev) => ({
                      ...prev,
                      context_window: isNaN(val) || val < 1000 ? 110000 : val,
                    }));
                  }}
                  className="w-28 h-8 text-right"
                />
              </div>

              <div className="form-row-inline">
                <div className="form-row-inline-label">
                  <span className="title">Max Output Tokens</span>
                  <span className="hint">Max output per request (tokens)</span>
                </div>
                <Input
                  id="max_tokens"
                  type="number"
                  step="1000"
                  min="256"
                  value={llm?.max_tokens ?? 8000}
                  onChange={(e) => {
                    const val = parseInt(e.target.value);
                    setLlm((prev) => ({
                      ...prev,
                      max_tokens: isNaN(val) || val < 256 ? 8000 : val,
                    }));
                  }}
                  className="w-28 h-8 text-right"
                />
              </div>
            </div>
          </div>

          {saveErrorMsg !== '' && (
            <Alert className="bg-destructive/10 dark:bg-destructive/20 border-none">
              <AlertCircleIcon className="h-4 w-4 !text-destructive" />
              <AlertTitle>{saveErrorMsg}</AlertTitle>
            </Alert>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setIsOpen(false)}>
            {t('common.cancel') || 'Cancel'}
          </Button>
          <Button onClick={handleSubmit}>
            {displayIsAdd ? 'Create LLM' : t('common.save')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
